/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package example.demonstration;

public final class R {
    public static final class array {
        public static final int new_in_version_changes=0x7f050001;
        public static final int new_in_version_versioncode=0x7f050000;
    }
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int barColor_1=0x7f01001f;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int barColor_2=0x7f010020;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int basePosDX=0x7f01000a;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int basePosDY=0x7f01000b;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int childHeight=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int childWidth=0x7f010004;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int color_1=0x7f01001b;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int color_2=0x7f01001c;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int color_3=0x7f01001d;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int dMax=0x7f010014;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int dMin=0x7f010013;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fillColor=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int horizontalSpacing=0x7f010002;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_dx=0x7f01000e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_dy=0x7f01000f;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_x=0x7f010000;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_y=0x7f010001;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int maxValue=0x7f01001e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int minVerticalSpacing=0x7f010003;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int outlineColor=0x7f010009;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int regionHeight=0x7f01000d;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int regionWidth=0x7f01000c;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int sampleNum=0x7f010010;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeColor=0x7f010021;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeWidth=0x7f010022;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeWidth_1=0x7f010018;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeWidth_2=0x7f010019;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int strokeWidth_3=0x7f01001a;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSize=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useChannel_1=0x7f010015;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useChannel_2=0x7f010016;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useChannel_3=0x7f010017;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int vMax=0x7f010012;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int vMin=0x7f010011;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int surfaceView=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040002;
        public static final int btn_get_involved_caption=0x7f040003;
        public static final int dialog_benchmark_submit_message=0x7f040008;
        public static final int dialog_benchmark_submit_title=0x7f040007;
        public static final int dialog_benchmarks_submit_please_message=0x7f04000a;
        public static final int dialog_benchmarks_submit_please_title=0x7f040009;
        public static final int dialog_first_app_launch_message=0x7f040005;
        public static final int dialog_first_app_launch_title=0x7f040004;
        public static final int dialog_modplayerexample_loading_to_external_message=0x7f04000c;
        public static final int dialog_modplayerexample_loading_to_external_title=0x7f04000b;
        public static final int dialog_new_in_this_version_title=0x7f040006;
        /**  Examples 
         */
        public static final int example_analogonscreencontrol=0x7f04001b;
        public static final int example_analogonscreencontrols=0x7f04001c;
        public static final int example_animatedsprites=0x7f04001d;
        /**  Apps 
         */
        public static final int example_app_cityradar=0x7f04005c;
        public static final int example_augmentedreality=0x7f04001e;
        public static final int example_augmentedrealityhorizon=0x7f04001f;
        public static final int example_autoparallaxbackground=0x7f040020;
        /**  Benchmarks 
         */
        public static final int example_benchmark_animation=0x7f040054;
        public static final int example_benchmark_particlesystem=0x7f040055;
        public static final int example_benchmark_physics=0x7f040056;
        public static final int example_benchmark_shapemodifier=0x7f040057;
        public static final int example_benchmark_sprite=0x7f040058;
        public static final int example_benchmark_tickertext=0x7f040059;
        public static final int example_boundcamera=0x7f040021;
        public static final int example_changeabletext=0x7f040022;
        public static final int example_collisiondetection=0x7f040023;
        public static final int example_colorkeytexturesourcedecorator=0x7f040024;
        public static final int example_coordinateconversion=0x7f040025;
        public static final int example_customfont=0x7f040026;
        public static final int example_digitalonscreencontrol=0x7f040027;
        public static final int example_easefunction=0x7f040028;
        public static final int example_game_racer=0x7f04005b;
        /**  Games 
         */
        public static final int example_game_snake=0x7f04005a;
        public static final int example_imageformats=0x7f040029;
        public static final int example_levelloader=0x7f04002a;
        public static final int example_line=0x7f04002b;
        public static final int example_loadtexture=0x7f04002c;
        public static final int example_menu=0x7f04002d;
        public static final int example_modplayer=0x7f04002e;
        public static final int example_movingball=0x7f04002f;
        public static final int example_multiplayer=0x7f040030;
        public static final int example_multitouch=0x7f040031;
        public static final int example_music=0x7f040032;
        public static final int example_particlesystemcool=0x7f040035;
        public static final int example_particlesystemnexus=0x7f040036;
        public static final int example_particlesystemsimple=0x7f040037;
        public static final int example_pathmodifier=0x7f040034;
        public static final int example_pause=0x7f040033;
        public static final int example_physics=0x7f040039;
        public static final int example_physicscollisionfiltering=0x7f040038;
        public static final int example_physicsfixedstep=0x7f04003a;
        public static final int example_physicsjump=0x7f04003c;
        public static final int example_physicsremove=0x7f04003d;
        public static final int example_physicsrevolutejoint=0x7f04003b;
        public static final int example_pinchzoom=0x7f04003e;
        public static final int example_rectangle=0x7f04003f;
        public static final int example_repeatingspritebackground=0x7f040040;
        public static final int example_rotation3d=0x7f040041;
        public static final int example_shapemodifier=0x7f040042;
        public static final int example_shapemodifierirregular=0x7f040043;
        public static final int example_sound=0x7f040044;
        public static final int example_splitscreen=0x7f040045;
        public static final int example_sprite=0x7f040046;
        public static final int example_spriteremove=0x7f040047;
        public static final int example_strokefont=0x7f040048;
        public static final int example_submenu=0x7f040049;
        public static final int example_text=0x7f04004a;
        public static final int example_textmenu=0x7f04004b;
        public static final int example_textureoptions=0x7f04004c;
        public static final int example_tickertext=0x7f04004e;
        public static final int example_tmxtiledmap=0x7f04004d;
        public static final int example_touchdrag=0x7f04004f;
        public static final int example_unloadresources=0x7f040050;
        public static final int example_updatetexture=0x7f040051;
        public static final int example_xmllayout=0x7f040052;
        public static final int example_zoom=0x7f040053;
        public static final int examplegroup_advanced=0x7f040015;
        public static final int examplegroup_app=0x7f040018;
        public static final int examplegroup_audio=0x7f040014;
        public static final int examplegroup_background=0x7f040016;
        public static final int examplegroup_benchmark=0x7f04001a;
        public static final int examplegroup_game=0x7f040019;
        public static final int examplegroup_modifier_and_animation=0x7f04000e;
        public static final int examplegroup_multiplayer=0x7f040011;
        public static final int examplegroup_other=0x7f040017;
        public static final int examplegroup_particlesystems=0x7f040010;
        public static final int examplegroup_physics=0x7f040012;
        /**  Example-Groups 
         */
        public static final int examplegroup_simple=0x7f04000d;
        public static final int examplegroup_text=0x7f040013;
        public static final int examplegroup_touch=0x7f04000f;
        public static final int tv_xmllayoutexample_above=0x7f040000;
        public static final int tv_xmllayoutexample_below=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a MyAbsoluteLayout_Layout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyAbsoluteLayout_Layout_layout_x example.demonstration:layout_x}</code></td><td></td></tr>
           <tr><td><code>{@link #MyAbsoluteLayout_Layout_layout_y example.demonstration:layout_y}</code></td><td></td></tr>
           </table>
           @see #MyAbsoluteLayout_Layout_layout_x
           @see #MyAbsoluteLayout_Layout_layout_y
         */
        public static final int[] MyAbsoluteLayout_Layout = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#layout_x}
          attribute's value can be found in the {@link #MyAbsoluteLayout_Layout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:layout_x
        */
        public static final int MyAbsoluteLayout_Layout_layout_x = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#layout_y}
          attribute's value can be found in the {@link #MyAbsoluteLayout_Layout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:layout_y
        */
        public static final int MyAbsoluteLayout_Layout_layout_y = 1;
        /** Attributes that can be used with a MyContextLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyContextLayout_basePosDX example.demonstration:basePosDX}</code></td><td></td></tr>
           <tr><td><code>{@link #MyContextLayout_basePosDY example.demonstration:basePosDY}</code></td><td></td></tr>
           <tr><td><code>{@link #MyContextLayout_regionHeight example.demonstration:regionHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #MyContextLayout_regionWidth example.demonstration:regionWidth}</code></td><td></td></tr>
           </table>
           @see #MyContextLayout_basePosDX
           @see #MyContextLayout_basePosDY
           @see #MyContextLayout_regionHeight
           @see #MyContextLayout_regionWidth
         */
        public static final int[] MyContextLayout = {
            0x7f01000a, 0x7f01000b, 0x7f01000c, 0x7f01000d
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#basePosDX}
          attribute's value can be found in the {@link #MyContextLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:basePosDX
        */
        public static final int MyContextLayout_basePosDX = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#basePosDY}
          attribute's value can be found in the {@link #MyContextLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:basePosDY
        */
        public static final int MyContextLayout_basePosDY = 1;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#regionHeight}
          attribute's value can be found in the {@link #MyContextLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:regionHeight
        */
        public static final int MyContextLayout_regionHeight = 3;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#regionWidth}
          attribute's value can be found in the {@link #MyContextLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:regionWidth
        */
        public static final int MyContextLayout_regionWidth = 2;
        /** Attributes that can be used with a MyContextLayout_Layout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyContextLayout_Layout_layout_dx example.demonstration:layout_dx}</code></td><td></td></tr>
           <tr><td><code>{@link #MyContextLayout_Layout_layout_dy example.demonstration:layout_dy}</code></td><td></td></tr>
           </table>
           @see #MyContextLayout_Layout_layout_dx
           @see #MyContextLayout_Layout_layout_dy
         */
        public static final int[] MyContextLayout_Layout = {
            0x7f01000e, 0x7f01000f
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#layout_dx}
          attribute's value can be found in the {@link #MyContextLayout_Layout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:layout_dx
        */
        public static final int MyContextLayout_Layout_layout_dx = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#layout_dy}
          attribute's value can be found in the {@link #MyContextLayout_Layout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:layout_dy
        */
        public static final int MyContextLayout_Layout_layout_dy = 1;
        /** Attributes that can be used with a MyGraphView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyGraphView_color_1 example.demonstration:color_1}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_color_2 example.demonstration:color_2}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_color_3 example.demonstration:color_3}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_dMax example.demonstration:dMax}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_dMin example.demonstration:dMin}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_sampleNum example.demonstration:sampleNum}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_strokeWidth_1 example.demonstration:strokeWidth_1}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_strokeWidth_2 example.demonstration:strokeWidth_2}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_strokeWidth_3 example.demonstration:strokeWidth_3}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_useChannel_1 example.demonstration:useChannel_1}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_useChannel_2 example.demonstration:useChannel_2}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_useChannel_3 example.demonstration:useChannel_3}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_vMax example.demonstration:vMax}</code></td><td></td></tr>
           <tr><td><code>{@link #MyGraphView_vMin example.demonstration:vMin}</code></td><td></td></tr>
           </table>
           @see #MyGraphView_color_1
           @see #MyGraphView_color_2
           @see #MyGraphView_color_3
           @see #MyGraphView_dMax
           @see #MyGraphView_dMin
           @see #MyGraphView_sampleNum
           @see #MyGraphView_strokeWidth_1
           @see #MyGraphView_strokeWidth_2
           @see #MyGraphView_strokeWidth_3
           @see #MyGraphView_useChannel_1
           @see #MyGraphView_useChannel_2
           @see #MyGraphView_useChannel_3
           @see #MyGraphView_vMax
           @see #MyGraphView_vMin
         */
        public static final int[] MyGraphView = {
            0x7f010010, 0x7f010011, 0x7f010012, 0x7f010013,
            0x7f010014, 0x7f010015, 0x7f010016, 0x7f010017,
            0x7f010018, 0x7f010019, 0x7f01001a, 0x7f01001b,
            0x7f01001c, 0x7f01001d
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#color_1}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:color_1
        */
        public static final int MyGraphView_color_1 = 11;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#color_2}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:color_2
        */
        public static final int MyGraphView_color_2 = 12;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#color_3}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:color_3
        */
        public static final int MyGraphView_color_3 = 13;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#dMax}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:dMax
        */
        public static final int MyGraphView_dMax = 4;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#dMin}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:dMin
        */
        public static final int MyGraphView_dMin = 3;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#sampleNum}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:sampleNum
        */
        public static final int MyGraphView_sampleNum = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#strokeWidth_1}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:strokeWidth_1
        */
        public static final int MyGraphView_strokeWidth_1 = 8;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#strokeWidth_2}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:strokeWidth_2
        */
        public static final int MyGraphView_strokeWidth_2 = 9;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#strokeWidth_3}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:strokeWidth_3
        */
        public static final int MyGraphView_strokeWidth_3 = 10;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#useChannel_1}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:useChannel_1
        */
        public static final int MyGraphView_useChannel_1 = 5;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#useChannel_2}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:useChannel_2
        */
        public static final int MyGraphView_useChannel_2 = 6;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#useChannel_3}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:useChannel_3
        */
        public static final int MyGraphView_useChannel_3 = 7;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#vMax}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:vMax
        */
        public static final int MyGraphView_vMax = 2;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#vMin}
          attribute's value can be found in the {@link #MyGraphView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:vMin
        */
        public static final int MyGraphView_vMin = 1;
        /** Attributes that can be used with a MyHorizontalGridView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyHorizontalGridView_childHeight example.demonstration:childHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #MyHorizontalGridView_childWidth example.demonstration:childWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #MyHorizontalGridView_horizontalSpacing example.demonstration:horizontalSpacing}</code></td><td></td></tr>
           <tr><td><code>{@link #MyHorizontalGridView_minVerticalSpacing example.demonstration:minVerticalSpacing}</code></td><td></td></tr>
           </table>
           @see #MyHorizontalGridView_childHeight
           @see #MyHorizontalGridView_childWidth
           @see #MyHorizontalGridView_horizontalSpacing
           @see #MyHorizontalGridView_minVerticalSpacing
         */
        public static final int[] MyHorizontalGridView = {
            0x7f010002, 0x7f010003, 0x7f010004, 0x7f010005
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#childHeight}
          attribute's value can be found in the {@link #MyHorizontalGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:childHeight
        */
        public static final int MyHorizontalGridView_childHeight = 3;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#childWidth}
          attribute's value can be found in the {@link #MyHorizontalGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:childWidth
        */
        public static final int MyHorizontalGridView_childWidth = 2;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#horizontalSpacing}
          attribute's value can be found in the {@link #MyHorizontalGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:horizontalSpacing
        */
        public static final int MyHorizontalGridView_horizontalSpacing = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#minVerticalSpacing}
          attribute's value can be found in the {@link #MyHorizontalGridView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:minVerticalSpacing
        */
        public static final int MyHorizontalGridView_minVerticalSpacing = 1;
        /** Attributes that can be used with a MyMixBarView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyMixBarView_barColor_1 example.demonstration:barColor_1}</code></td><td></td></tr>
           <tr><td><code>{@link #MyMixBarView_barColor_2 example.demonstration:barColor_2}</code></td><td></td></tr>
           <tr><td><code>{@link #MyMixBarView_maxValue example.demonstration:maxValue}</code></td><td></td></tr>
           <tr><td><code>{@link #MyMixBarView_strokeColor example.demonstration:strokeColor}</code></td><td></td></tr>
           <tr><td><code>{@link #MyMixBarView_strokeWidth example.demonstration:strokeWidth}</code></td><td></td></tr>
           </table>
           @see #MyMixBarView_barColor_1
           @see #MyMixBarView_barColor_2
           @see #MyMixBarView_maxValue
           @see #MyMixBarView_strokeColor
           @see #MyMixBarView_strokeWidth
         */
        public static final int[] MyMixBarView = {
            0x7f01001e, 0x7f01001f, 0x7f010020, 0x7f010021,
            0x7f010022
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#barColor_1}
          attribute's value can be found in the {@link #MyMixBarView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:barColor_1
        */
        public static final int MyMixBarView_barColor_1 = 1;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#barColor_2}
          attribute's value can be found in the {@link #MyMixBarView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:barColor_2
        */
        public static final int MyMixBarView_barColor_2 = 2;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#maxValue}
          attribute's value can be found in the {@link #MyMixBarView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:maxValue
        */
        public static final int MyMixBarView_maxValue = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#strokeColor}
          attribute's value can be found in the {@link #MyMixBarView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:strokeColor
        */
        public static final int MyMixBarView_strokeColor = 3;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#strokeWidth}
          attribute's value can be found in the {@link #MyMixBarView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:strokeWidth
        */
        public static final int MyMixBarView_strokeWidth = 4;
        /** Attributes that can be used with a MyOutlineTextView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MyOutlineTextView_fillColor example.demonstration:fillColor}</code></td><td></td></tr>
           <tr><td><code>{@link #MyOutlineTextView_outlineColor example.demonstration:outlineColor}</code></td><td></td></tr>
           <tr><td><code>{@link #MyOutlineTextView_text example.demonstration:text}</code></td><td></td></tr>
           <tr><td><code>{@link #MyOutlineTextView_textSize example.demonstration:textSize}</code></td><td></td></tr>
           </table>
           @see #MyOutlineTextView_fillColor
           @see #MyOutlineTextView_outlineColor
           @see #MyOutlineTextView_text
           @see #MyOutlineTextView_textSize
         */
        public static final int[] MyOutlineTextView = {
            0x7f010006, 0x7f010007, 0x7f010008, 0x7f010009
        };
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#fillColor}
          attribute's value can be found in the {@link #MyOutlineTextView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:fillColor
        */
        public static final int MyOutlineTextView_fillColor = 2;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#outlineColor}
          attribute's value can be found in the {@link #MyOutlineTextView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:outlineColor
        */
        public static final int MyOutlineTextView_outlineColor = 3;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#text}
          attribute's value can be found in the {@link #MyOutlineTextView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:text
        */
        public static final int MyOutlineTextView_text = 0;
        /**
          <p>This symbol is the offset where the {@link example.demonstration.R.attr#textSize}
          attribute's value can be found in the {@link #MyOutlineTextView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name example.demonstration:textSize
        */
        public static final int MyOutlineTextView_textSize = 1;
    };
}
